#!/bin/bash

magenta="\033[1;35m"
green="\033[1;32m"
white="\033[1;37m"
blue="\033[1;34m"
red="\033[1;31m"
black="\033[1;30m"
yellow="\033[1;33m"
cyan="\033[1;36m"

get_os() {
    if [ -n "$ANDROID_ROOT" ]; then
        echo "Android"
        return
    fi
    if command -v uname >/dev/null 2>&1 && [ "$(uname -s)" = "Linux" ]; then
        if [ -f /etc/os-release ]; then
            . /etc/os-release
            os_name=$(echo "${NAME}" | sed 's/ GNU\/Linux//g' | sed 's/ Linux//g')
            echo "${os_name:-Linux}"
        else
            echo "Linux"
        fi
    else
        echo "Unknown OS"
    fi
}

get_os_lucky() {
    local options=($(get_os) $(get_os) $(get_os) $(get_os) $(get_os) $(get_os) "Meow Meow")
    echo "${options[$RANDOM % ${#options[@]}]}"
}

get_ram() {
    local mem_info=$(free -m | awk 'NR==2{printf "%.1f %.1f", $3/1024, $2/1024}')
    local used=$(echo $mem_info | awk '{print $1}')
    local total=$(echo $mem_info | awk '{print $2}')
    local percent=$(awk "BEGIN {printf \"%.0f\", ($used/$total)*100}")
    echo "${used}/${total}GB (${percent}%)"
}

echo -e "\t\t  "
echo -e "      ${red}/|${white}､"
echo -e "     (${green}°${red}､ ${green}｡${red} 7${nc}\t  ${red}OS${white}: $(get_os_lucky)"
echo -e "     |､  ~ヽ\t  ${green}Ram${white}: $(get_ram)"
echo -e "     じしf_,)ノ\t "
echo
echo -e "\t\t  ${magenta}███${green}███${white}███${blue}███${red}███${black}███${yellow}███${cyan}███"
echo 
